### ISSUE TITLE
Template vs. Progressive Enhancement

### ISSUE THREAD

**Issue by luisrock** [retrohacker/template#3]
Explain to a frontend newbie what is the use case? What's wrong with the HTML traditional file, leaving the js stuff for the interactions?

**Comment by retrohacker** [comment]
Nothing wrong with it. Strongly recommend it for the document web w/ progressive enhancement, since Tails/Tor users and GNU/FOSS advocates often have JS turned off - for good reason.

Template is for delivering applications to a browser. It lets me create a hierarchy of reusable components for large applications that would be both tedious and error-prone to maintain otherwise. Instead of rolling an iOS app, an Android app, a Windows app, a Mac app, a Linux app, a FreeBSD app, etc. etc. etc., I build a single app that is distributed via the web and expects a modern browser.

**Comment by retrohacker** [comment]
Template also works with progressive enhancement BTW - you can see it in action on https://persona.ink

The website is good ol' fashioned hand-crafted HTML. The embedded editors are all progressive enhancement.
